### ISSUE TITLE
ProxyHeadersMiddleware crashes with gunicorn 24.1.0: AttributeError 'str' object has no attribute '_version'

### ISSUE THREAD

**Issue by user-Roma** [encode/uvicorn#2792]
### Initial Checks

- [x] I confirm this was discussed, and the maintainers suggest I open an issue.
- [x] I'm aware that if I created this issue without a discussion, it may be closed without a response.

### Discussion Link

```Text
https://github.com/Kludex/uvicorn/discussions/2791
```

### Summary
`_TrustedHosts` in `proxy_headers.py` crashes when used with gunicorn 24.1.0 due to type mismatch in trusted hosts handling.

### Versions
- uvicorn: 0.40.0
- gunicorn: 24.1.0 (works fine with 24.0.0)
- uvicorn-worker: 0.4.0
- Python: 3.13

### Error
```python
File "/opt/pysetup/venv/lib/python3.13/site-packages/uvicorn/middleware/proxy_headers.py", line 95, in __init__
    if "/" in host:
       ^^^^^^^^^^^
File "/usr/local/lib/python3.13/ipaddress.py", line 741, in __contains__
    if self._version != other._version:
                        ^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute '_version'
```

### Root Cause
Gunicorn 24.1.0 added CIDR network support ([PR #3449](https://github.com/benoitc/gunicorn/pull/3449)) and now passes pre-parsed `ipaddress.IPv4Network` objects to uvicorn worker instead of raw strings.

In `_TrustedHosts.__init__`, the code attempts `if "/" in host` to detect CIDR notation, but `host` is already an `IPv4Network` object. The `in` operator triggers `IPv4Network.__contains__()`, which expects an IP address object, not a string `"/"`.

### Expected Behavior
Uvicorn should handle both string and pre-parsed ipaddress objects from gunicorn.

### Workaround
Pin gunicorn to version < 24.1.0:
```
pip install gunicorn==24.0.0
```

### Example Code

```Python

```

### Python, Uvicorn & OS Version

```Text
Running uvicorn 0.40.0 with CPython 3.13.x on Linux
```
